/**
 * Formats analysis data for export
 */
export function formatAnalysisForExport(analysis) {
  if (analysis.error) {
    return `RoleAudit Analysis Report\n\n${analysis.title}\n${analysis.message}\n\n${analysis.guidance.join('\n')}`;
  }

  const score = analysis.scoreExplanation?.overallExplanation?.score || analysis.score;
  const band = analysis.band || 'Not Available';
  
  let report = `RoleAudit Role Readiness Analysis Report\n`;
  report += `Generated: ${new Date().toLocaleString()}\n`;
  report += `\n${'='.repeat(50)}\n\n`;
  
  report += `OVERALL READINESS: ${score} / 100\n`;
  report += `Band: ${band}\n`;
  
  if (analysis.scoreExplanation?.overallExplanation?.context) {
    report += `\n${analysis.scoreExplanation.overallExplanation.context}\n`;
  }
  
  // Score Breakdown
  if (analysis.scoreExplanation) {
    report += `\n${'='.repeat(50)}\n`;
    report += `SCORE BREAKDOWN\n`;
    report += `${'='.repeat(50)}\n\n`;
    
    report += `Base Readiness: ${analysis.scoreExplanation.baseReadinessScore}/100\n`;
    
    if (analysis.scoreExplanation.dimensionBreakdown) {
      const dimensions = {
        relevance: 'Role Alignment',
        depth: 'Skill Realism',
        adaptability: 'Adaptability',
        environmentFit: 'Context Fit'
      };
      
      Object.entries(analysis.scoreExplanation.dimensionBreakdown).forEach(([key, dim]) => {
        if (key !== 'riskPenalty' && dim.score !== undefined) {
          report += `${dimensions[key] || key}: ${dim.score}/${dim.maxScore}\n`;
        }
      });
    }
    
    if (analysis.scoreExplanation.riskPenalty > 0) {
      report += `Risk Deduction: -${analysis.scoreExplanation.riskPenalty} points\n`;
    }
  }
  
  // Cover Letter Impact
  if (analysis.coverLetterImpact) {
    report += `\n${'='.repeat(50)}\n`;
    report += `COVER LETTER IMPACT\n`;
    report += `${'='.repeat(50)}\n\n`;
    report += `${analysis.coverLetterImpact.modifier > 0 ? '+' : ''}${analysis.coverLetterImpact.modifier} points\n`;
    report += `${analysis.coverLetterImpact.explanation}\n`;
  }
  
  // Role Requirements
  if (analysis.roleSummary && analysis.roleSummary.length > 0) {
    report += `\n${'='.repeat(50)}\n`;
    report += `ROLE REQUIREMENTS\n`;
    report += `${'='.repeat(50)}\n\n`;
    
    analysis.roleSummary.forEach((item, i) => {
      report += `${i + 1}. ${item.dimension}: ${item.claim}\n`;
      if (item.evidence && item.evidence.length > 0) {
        report += `   Evidence: ${item.evidence.join('; ')}\n`;
      }
      report += '\n';
    });
  }
  
  // Strengths
  if (analysis.strengths && analysis.strengths.length > 0) {
    report += `\n${'='.repeat(50)}\n`;
    report += `STRENGTHS\n`;
    report += `${'='.repeat(50)}\n\n`;
    
    analysis.strengths.forEach((strength, i) => {
      report += `${i + 1}. ${strength.dimension}\n`;
      report += `   ${strength.explanation}\n`;
      if (strength.resumeEvidence && strength.resumeEvidence.length > 0) {
        report += `   Evidence: ${strength.resumeEvidence.join('; ')}\n`;
      }
      report += '\n';
    });
  }
  
  // Gaps
  if (analysis.gaps && analysis.gaps.length > 0) {
    report += `\n${'='.repeat(50)}\n`;
    report += `GAPS TO ADDRESS\n`;
    report += `${'='.repeat(50)}\n\n`;
    
    analysis.gaps.forEach((gap, i) => {
      report += `${i + 1}. ${gap.dimension}\n`;
      report += `   ${gap.explanation}\n`;
      report += `   JD Expects: ${gap.jdExpectation?.inference || 'N/A'}\n`;
      report += `   Resume Shows: ${gap.resumeEvidence?.inference || 'N/A'}\n`;
      report += '\n';
    });
  }
  
  // Risks
  if (analysis.risks && analysis.risks.length > 0) {
    report += `\n${'='.repeat(50)}\n`;
    report += `POTENTIAL RISKS\n`;
    report += `${'='.repeat(50)}\n\n`;
    
    analysis.risks.forEach((risk, i) => {
      report += `${i + 1}. ${risk.dimension}\n`;
      report += `   ${risk.explanation}\n`;
      if (risk.evidence && risk.evidence.length > 0) {
        report += `   Evidence: ${risk.evidence.join('; ')}\n`;
      }
      if (risk.detail) {
        report += `   ${risk.detail}\n`;
      }
      report += '\n';
    });
  }
  
  report += `\n${'='.repeat(50)}\n`;
  report += `Report generated by RoleAudit\n`;
  report += `Evidence-based role readiness analysis\n`;
  
  return report;
}

/**
 * Downloads analysis as a text file
 */
export function downloadAnalysis(analysis) {
  const content = formatAnalysisForExport(analysis);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `roleaudit-analysis-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copies analysis to clipboard
 */
export async function copyAnalysisToClipboard(analysis) {
  const content = formatAnalysisForExport(analysis);
  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch (err) {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = content;
    textArea.style.position = 'fixed';
    textArea.style.opacity = '0';
    document.body.appendChild(textArea);
    textArea.select();
    try {
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (fallbackErr) {
      document.body.removeChild(textArea);
      return false;
    }
  }
}

